### PR TITLE
Set "nonce" on Inline Style if Exists

### PR DESCRIPTION
**Pull request by rience**
We need to use "unsafe-inline" for CSS in our Content Security Policy - otherwise styles for Friendly Captcha are not being loaded. This small PR fixes that and looks into meta of page to see if nonce is set in header. If it is - then it's being used for inline css element.

### CODE REVIEW

**Comment by gzuidhof** [comment]
If I understand correctly, this `csp-nonce` would be specific for the stylesheet of FC. I'm hesitant to merge this as it may have effects for users that happen to have a meta tag set with the same name for a different usecase. In other words: I think it may be a bit too specific to merge.

I would say perhaps it makes sense to add the stylesheet yourself (with a nonce), the [contents can be found here](https://github.com/FriendlyCaptcha/friendly-challenge/blob/master/src/styles.css). As long as it has the `frc-style` id the widget won't inject another stylesheet. 

I imagine you have already worked your way around it, so I imagine this is more for future visitors of this issue.

**Comment by rience** [comment]
Hi,

I get what you're saying. We're using it in Rails and it does have a helper to generate meta tag `csp-nonce` and that's how 3rd party libraries can add custom stylesheets. That's why I assumed it's de-facto standard but apparently it's not.

We do add stylesheets ourselves at the moment but it'd be good addition to library to be able to handle it automatically. Especially because CSP by default disables unsafe execution of CSS and JS.

Would you accept PR that accepts `nonce` in `WidgetInstance` constructor (through `options`)?

**Comment by rience** [comment]
Hi @gzuidhof,

PR updated - let me know what do you think.

**Comment by gzuidhof** [comment]
Yes that's a good idea!

Maybe we can call it `styleNonce` to make it a bit more obvious what it's for. Could you add an entry to the docs file [here](https://github.com/FriendlyCaptcha/friendly-challenge/blob/master/docs/widget_api.md#javascript-api) as well to briefly explain it?

**Comment by rience** [comment]
Hi @gzuidhof,

Take a look at PR now - I've taken your feedback and applied it.

**Review by gzuidhof — APPROVED** [review]
It looks great, thank you for the contribution! Let me know when you are happy for us to merge it.

**Comment by rience** [comment]
Go ahead and merge that. Looking forward to pull in new version.

**Pull request merged**
