### PR TITLE
Attach widget instance to Widget DOM element

### PR DESCRIPTION
**Pull request by JPustkuchen**
See https://github.com/FriendlyCaptcha/friendly-challenge/issues/81

### CODE REVIEW

**Comment by JPustkuchen** [comment]
SUPER COOL @merlinfuchs, thank you very much for that super fast reaction! :)

Came from demand in our Drupal Module: https://www.drupal.org/project/friendlycaptcha/issues/3262012

**Comment by JPustkuchen** [comment]
PS: I wrote the code as reference / example in the browser, so thank you for cleaning this up. Was important of course ;)

**Comment by gzuidhof** [comment]
Looks great - happy to merge, thank you for the contribution!

**Comment by JPustkuchen** [comment]
That went fast! 🚀 😲 
Thank you so much!! 👍

**Pull request merged**
