### PR TITLE
Add Arabic localization

### PR DESCRIPTION
**Pull request by achaabni**
Hi,
I added Arabic localization and also added a forgotten semi-colon on the last update.

### CODE REVIEW

**Comment by merlinfuchs** [comment]
Looks good, thank you!

**Comment by merlinfuchs** [comment]
The new localization is now available in version 0.9.18 :)

**Comment by achaabni** [comment]
> The new localization is now available in version 0.9.18 :)

great, thank you.

**Comment by achaabni** [comment]
TENET-friendlyCaptcha-ar
Just test the latest version and the localization is here.
Thank you for the quick deployment

**Pull request merged**
